lint: {}
nf_core_version: 3.0.3.dev0
repository_type: pipeline
template:
  author: bar
  description: veryfirstpipeline with minimal interface
  force: true
  is_nfcore: true
  name: foo
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.0dev
update: null
