contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #foo channel"
    url: https://nfcore.slack.com/channels/foo
    about: Discussion about the nf-core/foo pipeline
